version: 2
jobs:
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: Test and deploy if master
          command: |
            pip install -r requirements.txt
            doc8 docs
            sphinx-build -W docs staged
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                touch staged/.nojekyll
                git config --global user.email "dankolbman@gmail.com"
                git config --global user.name "Dan Kolbman"
                git checkout gh-pages
                git pull origin gh-pages
                cp -r staged/* ./
                rm -r staged
                git add -A .
                git commit --allow-empty -m ":recycle: Update docs site"
                git push -q https://${GITHUB_TOKEN}@github.com/kids-first/kf-developer-handbook.git
            fi
